# Generated by Django 4.0.4 on 2022-06-19 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcontrollerserver', '0002_game_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
