# Generated by Django 4.0.4 on 2022-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcontrollerserver', '0008_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ads',
            name='picture',
            field=models.ImageField(blank=True, upload_to='ads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
