# Generated by Django 4.0.5 on 2022-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcontrollerserver', '0009_alter_ads_description_alter_ads_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='picture',
            field=models.ImageField(blank=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
