# Generated by Django 4.0.5 on 2022-07-10 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcontrollerserver', '0010_alter_ads_picture_alter_game_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
