# Generated by Django 4.0.4 on 2022-07-18 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carcontrollerserver', '0012_alter_appuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
