# Generated by Django 4.0.4 on 2022-07-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcontrollerserver', '0013_alter_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='picture',
            field=models.ImageField(upload_to='ads/'),
        ),
    ]
